application: project-marosf
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: wsgi.application

libraries:
- name: django
  version : "1.5"

- name: ssl
  version: "latest"

builtins:
- deferred : on
- django_wsgi: on

